markdown: kramdown
theme: minima
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia esto si tu rama principal es diferente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby (si usas Jekyll)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'  # o la versión que uses

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site
        run: bundle exec jekyll build  # Este comando puede variar según tu configuración

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Este es el directorio donde se genera el sitio de Jekyll
